apiVersion: 1
contactPoints:
  - orgId: 1
    name: 'Discord-Alerts'
    receivers:
      - uid: 'discord-receiver-1'
        type: 'discord'
        settings:
          url: 'DISCORD_URL_PLACEHOLDER'
          message: '{{ .CommonAnnotations.summary }}\n{{ .CommonAnnotations.description }}'

policies:
  - orgId: 1
    receiver: 'Discord-Alerts'
    group_by: ['alertname']