version: '3.8'

services:
  java-app:
    image: ${DOCKER_IMAGE_NAME}
    container_name: java-app
    ports:
      - "8080:8080"
    restart: always

  # Monitoring: Prometheus
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - java-app

  # Monitoring: Grafana
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin