---
- name: "Konfiguracja serwera: Docker, Aplikacja i Monitoring"
  hosts: all
  become: yes
  tasks:
    - name: "Aktualizacja repozytoriów"
      apt:
        update_cache: yes

    - name: "Instalacja Dockera i Docker Compose"
      apt:
        name:
          - docker.io
          - docker-compose
        state: present

    - name: "Uruchomienie usługi Docker"
      service:
        name: docker
        state: started
        enabled: yes

    - name: "Tworzenie katalogu głównego aplikacji"
      file:
        path: /home/ubuntu/app
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0755'

    - name: "Kopiowanie plików głównych"
      copy:
        src: "{{ item }}"
        dest: /home/ubuntu/app/
        owner: ubuntu
        group: ubuntu
      with_items:
        - ./docker-compose.yml
        - ./prometheus.yml

    - name: "Kopiowanie całej struktury folderu grafana"
      copy:
        src: ./grafana
        dest: /home/ubuntu/app/
        owner: ubuntu
        group: ubuntu
        mode: '0755'

    - name: "Ustawienie uprawnień dla User ID 472 (Grafana)"
      file:
        path: "/home/ubuntu/app/grafana"
        owner: "472"
        group: "472"
        state: directory
        recurse: yes

    - name: "Uruchomienie stosu Docker Compose"
      shell: "export DOCKER_IMAGE_NAME={{ docker_image_name }} && cd /home/ubuntu/app && docker-compose pull && docker-compose up -d --force-recreate"