name: "Infrastructure Destruction"

on:
  workflow_dispatch:

jobs:
  terraform-destroy:
    name: "Cleanup AWS Environment"
    runs-on: ubuntu-latest
    
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v4

      - name: "Setup Terraform"
        uses: hashicorp/setup-terraform@v3

      - name: "Terraform Destroy (Selective)"
        id: destroy_step
        run: |
          cd terraform
          terraform init -reconfigure
          # Musimy podać zmienne, inaczej Terraform pyta o nie w konsoli i zawiesza proces
          terraform destroy -auto-approve \
            -var="key_name=${{ secrets.TF_VAR_KEY_NAME }}" \
            -var="public_key=${{ secrets.TF_VAR_PUBLIC_KEY }}" \
            -target=aws_instance.app_server \
            -target=aws_security_group.main_sg \
            -target=aws_subnet.main_subnet \
            -target=aws_vpc.main_vpcbnet \
            -target=aws_vpc.main_vpc